name: device_apps_example
description: Demonstrates how to use the device_apps plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_apps:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"